### PR TITLE
WinUI 3 support

### LINKED ISSUE #31: Winui 3
Wondering if you plan on introducing a Winui 3 set?

Would be very welcome

### PR DESCRIPTION
**Pull request by fubar-coder**
This tries to fix #31, but is blocked due to microsoft/microsoft-ui-xaml#9959.

This PR contains a fully functional DLL and demo application, which are mostly copies from the WPF implementation.

Differences from the WPF implementation include:

- The `Data` property returns a `Geometry` object now

Requirements:

- .NET SDK 8.0.401
- VS 2022 17.11.2

# TODO

- [X] Find workaround/fix for microsoft/microsoft-ui-xaml#9959
- [X] Find workaround for microsoft/CsWinRT#1736
- [X] Update build configuration to create a successful build

### CODE REVIEW

**Comment by SKProCH** [comment]
Hello, @fubar-coder 

Can you also include a github actions script changes to support auto building library for auto publishing on nuget on icons change?

**Comment by fubar-coder** [comment]
Adding a `EnableMsixTooling` property fixes a part of the problems I encountered. The missing `Platform.xml` might be a bug in CsWinRT (microsoft/CsWinRT#1736).

The build environment needs an installed Win 10 SDK (including the UAP platform stuff), which means that the build must(?) be run under windows, using the - for example - [ChristopheLav/windows-sdk-install build action](https://github.com/ChristopheLav/windows-sdk-install), but I haven't tested it yet.

**Comment by SKProCH** [comment]
Yep, current build environment is already on windows, since i also need to build WPF library, so probably windows not a problem here. But i also doesn't success while trying to setup CI build under windows, so probably it also should be in scope of this PR.

**Comment by fubar-coder** [comment]
@SKProCH PR is ready for review

**Review by fubar-coder — COMMENTED** [review]
I'd like to lower the required SDK version to 10.0.18362.0, because 10.0.22621.0 seems too high. There are still some Win10 machines out there 😄

**Comment by SKProCH** [comment]
Feed free to do it, if it would work.

**Comment by fubar-coder** [comment]
The package requires the SDK version 10.0.18362.0, while the demo application requires 10.0.19041.0, due to its reliance on Rx.NET.

**Review by SKProCH — APPROVED** [review]

**Pull request merged**
